Fix the Operator example for GitHub
### Overview

This PR updates the GitHub example for the Operator to use `podTemplateSpec` to inject the secret instead of using the `secrets` property.

### Background

Currently, the `secrets` struct in the MCPServer CRD does not function, users get an error (see #521):

```
Error: failed to get secrets: secret not found: github-token/token (none provider doesn't store secrets)
```

While we work on a permanent solution to secrets handling in K8s, injecting secrets via `podTemplateSpec` works.